### ISSUE TITLE
Header Search Paths

### ISSUE THREAD

**Issue by nycoliver** [frostney/react-native-create-library#11]
Hi, I couldn't get this to work without running `npm install react-native` and adding `$(SRCROOT)/../node_modules/react-native/React` to the xcode project header search paths. 

I feel like I'm missing something obvious... any guidance? Btw thanks for the awesome tool!

**Comment by emps** [comment]
usually ur react module should be installed using NPM, so ur module should be located inside 
UrAPP/node_modules/react-native-ur-module
and srcroot is  the path of 
UrAPP/node_modules/react-native-ur-module/ios
that will look for react and react native headers and libs
so u need config correctly that path if u put ur module inside node_modules during ur development so u need to do 2 folders back that is ../..
than enter /react and enter /react-native 
so in sum up it is
$(SRCROOT)/../../node_modules/react (recursive)
$(SRCROOT)/../../node_modules/react-native (recursive)
but if u put ur module outside of node_modules u can just give real paths untill u publish ur app with npm for public usuage

u can just give full paths from main root / till
/UrAPP/node_modules/react
/UrAPP/node_modules/react-native

**Comment by nycoliver** [comment]
Makes sense, thank you!

**Comment by vi3k** [comment]
<script>
function myFunction() {
    // Declare variables
    var input, filter, ul, li, a, i;
    input = document.getElementById('myInput');
    filter = input.value.toUpperCase();
    ul = document.getElementById("myUL");
    li = ul.getElementsByTagName('li');

    // Loop through all list items, and hide those who don't match the search query
    for (i = 0; i < li.length; i++) {
        a = li[i].getElementsByTagName("a")[0];
        if (a.innerHTML.toUpperCase().indexOf(filter) > -1) {
            li[i].style.display = "";
        } else {
            li[i].style.display = "none";
        }
    }
}
</script>
Try it Yourself »

<a href="http://www.hotstars.co.in/">Visit W3Schools</a>
