### ISSUE TITLE
Generated Windows libraries should have unique GUID

### ISSUE THREAD

**Issue by rozele** [frostney/react-native-create-library#13]
Each project in a given native solution should have a unique GUID.  As such, you'll need to generate a GUID and parameterize here: https://github.com/frostney/react-native-create-library/blob/master/templates/windows.js#L10, here https://github.com/frostney/react-native-create-library/blob/master/templates/windows.js#L30-L53, and here https://github.com/frostney/react-native-create-library/blob/master/templates/windows.js#L195.

**Comment by frostney** [comment]
Thank you for creating the issue. I'll get right on that once I get home.

**Comment by rozele** [comment]
@frostney Already put up a PR :-)

**Comment by frostney** [comment]
Sweet, thank you so much!

![](https://media.giphy.com/media/JVdF14CQQH7gs/giphy.gif)

**Comment by frostney** [comment]
Thank you for your fixes. Much appreciated. I just released version 1.0.3 which includes the fixes from both of your pull requests from today.
