### ISSUE TITLE
Create an RNPM plugin for create-library

### ISSUE THREAD

**Issue by rozele** [frostney/react-native-create-library#2]
An alternative to publishing upstream, which may be more amenable to generating Windows libraries, would be to make this an RNPM plugin.  A [recent commit](https://github.com/rnpm/rnpm/commit/769b69264f035fe366132df777fab7f6fd3bf03f) to RNPM allows any packages that start with react-native-\* (which this does) to be recognized as a plugin.

Here's how we allow RNPM to pickup plugins from react-native-windows:
https://github.com/ReactWindows/react-native-windows/blob/master/package.json#L38-L40

**Comment by frostney** [comment]
This looks very interesting and I'm intrigued. This is definitely something I'll take a closer look during the next few days if I have a few hours to myself.

**Comment by grabbou** [comment]
Anyone actively working on that? I am up to adding support since that's very useful and idiomatic way of doing things.

**Comment by frostney** [comment]
All done! 🎉 🍾 

This has just been published as `3.0.2`.
