### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by vikeri** [frostney/react-native-create-library#22]
I see a lot of unanswered issues and a pull request that is not merged. Is this still up to date/usable?

**Comment by guyca** [comment]
I've used it a couple of times, most recently three weeks ago - works perfect for me.

**Comment by vikeri** [comment]
Perfect! Thanks, things move so fast in RN that sometimes these things can get outdated... Does it work with the link command btw?

**Comment by guyca** [comment]
No idea. I don't use link :)

**Comment by frostney** [comment]
It should work with `link`. If it doesn't, please create an issue 😄
Nevertheless, during the past couple of months I haven't been able to maintain my open source projects as much I would like have. If someone wants to join as a contributor, I'd be eternally grateful.
