### ISSUE TITLE
header file not found for ios framework

### ISSUE THREAD

**Issue by ben-hynt** [frostney/react-native-create-library#24]
I've included a framework in the xcode project for the RN library I'm creating.  Everything compiles fine when I build the ios project in the RN library, but once I npm install the library into my main RN project, run `react-native link <project-name>`, and then build in xcode, the included framework headers are not found.  

I checked the normal build settings (Header, Framework, and Library search paths) and they all have `$(inherited)` listed.  Any ideas why I'm receiving this compile error?

**Comment by bsy** [comment]
here's the repo for the library https://github.com/bsy/react-native-pollfish

**Comment by bsy** [comment]
@frostney any ideas?

**Comment by Jonovono** [comment]
@bsy How did you solve this? I think I am facing a similar issue

**Comment by kadikraman** [comment]
I ran into this issue as well. What I've ended up doing:
1) in the consuming project, add the dependency in the `.podfile` and `pod install`
2) in the library project, open `project.pbxproj` and add `"$(SRCROOT)/../../../ios/Pods/**",` to `HEADER_SEARCH_PATHS` in both debug and release.

It doesn't feel like the "correct" way to do it as surely `"$(inherited)"` should do the same thing. Nonetheless, it got the project building for now. I will update this comment if I ever find the correct way.

**Comment by tslater** [comment]
I'm a bit confused after reading this: https://facebook.github.io/react-native/docs/linking-libraries-ios.html, and after playing with react-native-create-library. I'm not sure how to manage cocoapods in the iOS part of my library. When would the pods be installed? Does react-native link do that?

**Comment by jasan-s** [comment]
native module i'm building uses firebase(installed through cocoa pods). I added `"$(SRCROOT)/../../../ios/Pods/**"` to header search path in the library and now in the Project that uses the native module I keep getting error at  `import firebase` that  `No such module 'Firebase' `
