### ISSUE TITLE
'React/RCTDefines.h' file not found

### ISSUE THREAD

**Issue by seiji619** [frostney/react-native-create-library#34]
I get this error whenever I create the library inside `node_modules` folder of one of my RN projects. Any thoughts?

**Comment by bang88** [comment]
Me too.

**Comment by seiji619** [comment]
@bang88 Actually, it's normal I think. When I linked the library with the main project, it worked without any more error.

**Comment by bang88** [comment]
But i want debug  the library

**Comment by seiji619** [comment]
You can do it on the main project.

**Comment by bang88** [comment]
Thanks i will try this ASAP, i have spend hours on this issues.. crazy

**Comment by frostney** [comment]
I'm sorry about this. I think it's mostly bad developer experience and I'm happy for pull requests that fix this issue or document this more clearly.
