### ISSUE TITLE
Create Xcode workspace at root of ios directory

### ISSUE THREAD

**Issue by Tableau-David-Potter** [frostney/react-native-create-library#35]
To facilitate the use of CocoaPods, could you modify the tool to generate an Xcode workspace?  The first thing I end up having to do is create a workspace and then add the project generated by this tool to that workspace.

**Comment by tslater** [comment]
The project currently generates a workspace? Should this be closed?

Side note: the workspace won't open on my machine. Is that expected? I get an error message:
"The document “ProjectName.xcworkspace” could not be opened."

**Comment by anoop4real** [comment]
I am creating project using CLI 2.0.1, I am not getting any workspace created.

**Comment by maicki** [comment]
The Xcode workspace creation works as expected after #52 will land it actually will also open now. A workspace will be created within the ios folder.

My question is just @Tableau-David-Potter and @frostney why do we need an Xcode workspace in the first place? If you integrate it via CocoaPods you just refer to the podspec and CocoaPods will just pull in the source file in your projects workspace. In fact I think we should remove creating a workspace in the first place as it's kind of useless.

**Comment by aleczadikian** [comment]
The worskspace is failing to open for me. Xcode 9.4.1.

**Comment by maicki** [comment]
After #52 landed the workspace can be opened again.

@aleczadikian Hey - can you please use master. Just tested it out and it should work from there. Thanks!

**Comment by zabojad** [comment]
Wa cannot open in XCode 10 the workspace generated with `react-native-create-library@3.1.2`.

**Comment by tbcshifter** [comment]
Any progress on getting the workspace working with XCode 10?

**Comment by Alyxdev-xyz** [comment]
The XML generated for Xcode's workspace contains a comment at the first line. Xcode doesn't like comments in XML. You can remove the line `// !$*UTF8*$!`

**Comment by 7934345** [comment]
> The XML generated for Xcode's workspace contains a comment at the first line. Xcode doesn't like comments in XML. You can remove the line `// !$*UTF8*$!`

edit this file(contents.xcworkspacedata) remove the first line `// !$*UTF8*$!` and I can open the xcworkspace
