### ISSUE TITLE
Xcode project fails to build

### ISSUE THREAD

**Issue by DavidPotter** [frostney/react-native-create-library#38]
When I attempt to build the Xcode project generated by this tool using Xcode 8.3.3, I get the following error in the .m file:

```
fatal error: 'React/RCTBridgeModule.h' file not found
#import <React/RCTBridgeModule.h>
        ^
```

Here are the steps I followed:

1. `react-native-create-library --prefix '' --package-identifier com.tableau --platforms ios,android Foo`
2. `yarn remove react-native --peer`
3. `yarn add react-native`
4. `yarn add react@16.0.0-alpha.12`
5. Create a new workspace in the ios directory.
6. Add the Xcode project to the workspace.
7. Update the project from the warning.
8. Build in Xcode.

**Comment by DavidPotter** [comment]
I found the problem.  There are a couple steps missing from the instructions.  Here is what I had to do:
1. Add a reference to the React Xcode project located at node_modules/react-native/React.
2. Add the resulting libReact.a file to the list under "Link Binary With Libraries" o the Build Phases tab of the library target.

Once I did that I was able to build.

**Comment by cinder92** [comment]
i have the same issue, but i dont understand to @DavidPotter :(
