### ISSUE TITLE
Error: more than one library with package name 'com.reactlibrary'

### ISSUE THREAD

**Issue by KjellConnelly** [frostney/react-native-create-library#45]
Hey guys, I've noticed after using react-native-create-library for more than one library, I'm getting this error message when building for android:

Error: more than one library with package name 'com.reactlibrary'

This is telling me that when you create the library, the library has the same package name. Can you fix this so it's unique next time? Also, where do I change this within my android code so it does work? Thanks!

**Comment by yinghang** [comment]
I can do a more detailed writeup, but in the meantime, take a look at this [brief explanation](https://en.wikipedia.org/wiki/Java_package#Package_naming_conventions)!

**Comment by maicki** [comment]
With the PR merged from above we are preventing creating libraries with the default name now. I will close this issue, please reopen if you don't think it's resolved. Thanks!
