### ISSUE TITLE
compile error RN 0.51, redefinition of 'RCTMethodInfo'

### ISSUE THREAD

**Issue by quincycs** [frostney/react-native-create-library#47]
I was able to fix the compiler error by changing the below

https://github.com/frostney/react-native-create-library/blob/master/templates/ios.js#L33

to

```
#if __has_include(<React/RCTBridgeModule.h>)
#import <React/RCTBridgeModule.h>
#else
#import "RCTBridgeModule.h"
#endif
```

**Comment by JoeyCurry** [comment]
How to use, can explain in detail?
