### ISSUE TITLE
--generate-example not working?

### ISSUE THREAD

**Issue by jgfidelis** [frostney/react-native-create-library#63]
I ran `react-native-create-library MyFancyLibrary --generate-example "true"` and it did not create an Example app, how should it be used?

I also tried `--generate-example true`

**Comment by dooboolab** [comment]
In addition to this, if you check the commands with `-h` option, `--generate-example` won't appear.

**Comment by sgong-pdftron** [comment]
FYI directly replace the npm installed version with the cloned version will work.

**Comment by maicki** [comment]
@jgfidelis @dooboolab Currently this feature is only available on master and not in the release version yet. Can you please try out master and let us know if this will work. Furthermore there is currently a PR out that improves the example generation, best is to create you example project from that branch: https://github.com/frostney/react-native-create-library/pull/75

**Comment by maicki** [comment]
As said above this feature is only available on master on at this time and after #75 landed it should be improved too. We are planning to release a new version pretty soon.

**Comment by brody2consult** [comment]
Too bad it is still not released (#78) now that #75 has landed.
