### ISSUE TITLE
Add postinstall removing of example

### ISSUE THREAD

**Issue by osdnk** [frostney/react-native-create-library#69]
Using the newest version from master with automatically generated example I faced a problem when I ran `react-native start`  with duplication of dependencies. 
`example` folder is being copied while installing `example`  (because of `file:../` dependency). The solution is imo to add some postinstall script (like [here](https://github.com/osdnk/react-native-haptics/blob/f4a859fd1ca26f99904415166ba8b9ae45bf9807/example/package.json#L8) I have done) :)

**Comment by osdnk** [comment]
Welp @xoxoxoooxx,
I don't remember clearly and didn't manage to find in history of my terminal.
But frankly speaking I didn't face anything unexpected following Readme. Take into consideration that I was using my fork with bumped version  ¯\_(ツ)_/¯.

**Comment by osdnk** [comment]
Oh, and maybe remember to remove "example" and "node_modules" from example/node_modules/yourlibname

**Comment by xoxoxoooxx** [comment]
Thank you, @osdnk.
I decided rebuild my library all over again, then everything is fined.

**Comment by maicki** [comment]
Hey all - this PR should fix this issue: #75 and does some more improvements around our example creation.
