### ISSUE TITLE
Consider auto-create project folder like "react-native init AwesomeProject"

### ISSUE THREAD

**Issue by esutton** [frostney/react-native-create-library#7]
For consistency with react-native init command line interface.

**Comment by frostney** [comment]
I really like the idea and all your suggestions from #1, thank you for writing all of that down. I agree with you on all points, but I would like to keep an option to have the most minimal project as well. Something along the lines of `--bare`.
I'm not sure when I will have time to tackle this issue though.

**Comment by esutton** [comment]
Maybe after I am smarter and have finished my iOS / Android native module, I can find time to work on an example app template with two or three example ReactMethods.

**Comment by esutton** [comment]
@frostney I see you are working on Bluetooth Low Energy ( BLE ).  I'll have to check those out.  

I am working on a Bluetooth Classic native module for iOS and Android.  On iOS you will need a device with a External Accessory EA protocol.

**Comment by frostney** [comment]
This just landed with `2.0.0`. After thinking about this I decided against a `--bare` option, as I believe now creating a folder improves the developer experience and should be the default behavior. It's easier to move a folder around than finding out which files have just been generated.

**Comment by esutton** [comment]
@frostney Thanks! Less is more! 

( I hate Starbucks because it has * too * many choices ;-)
