### ISSUE TITLE
what is the package for emitDeviceEvent in android?

### ISSUE THREAD

**Issue by roysG** [frostney/react-native-create-library#70]

**Comment by maicki** [comment]
@roysG Hey! It's build right into React Native. You can find a good blog post about it here: https://blog.callstack.io/sending-events-to-javascript-from-your-native-module-in-react-native-29244f890e04 or if you want to have it a bit abstracted away you can look into this library: https://github.com/maicki/react-native-event-bridge

**Comment by SeanPesce** [comment]
The above blog post link no longer works; for anyone who comes across this page, that post can now be found here (I also archived it on [https://archive.org](https://archive.org)):

[https://www.callstack.com/blog/sending-events-to-javascript-from-your-native-module-in-react-native](https://www.callstack.com/blog/sending-events-to-javascript-from-your-native-module-in-react-native)
