### ISSUE TITLE
Module does not appear in NativeModules object for iOS

### ISSUE THREAD

**Issue by eddieowens** [frostney/react-native-create-library#72]
### The problem
When adding the default iOS module into an app created by `react-native init`, the library's module does not appear in the `NativeModules` Javascript object.

### Steps to reproduce
1. Create an app called `myapp`
```bash
react-native init myapp
```
2. Create a library called `mylib`
```bash
react-native-create-library mylib
```
3. Add `mylib` as a dependency to `myapp` using [install-local](https://www.npmjs.com/package/install-local)
```bash
install-local --save ../mylib
```
4. Link `mylib`
```bash
react-native link react-native-mylib
```
5. Print out the `NativeModules` object in `App.js` in `myapp`
```javascript
import {NativeModules, ...} from 'react-native'
...
render() {
  console.log('modules! ', NativeModules);
  ...
}
```
6. Run the app and debug it remotely
```console
react-native run-ios
```
### Expected
The Module `RNMylib` should appear among all of the react native base native modules

### Actual
Only the react native base native modules appear and `RNMylib` cannot be used on the Javascript side of things.

### Relevant versions
`react-native: 0.56.0`
`react: 16.4.1`
`xcode: 9.4.1`
`simulator: iPhone 6 - 11.4`
`react-native-create-library: 3.1.2`
`react-native-cli: 2.0.1`

I do see the `RNMylib.xcodeproj` in my `Libraries` folder in xcode. It has also been added to the user headers search paths and is listed in the build settings. The `react-native link` command was definitely successful.

Any help with this would be greatly appreciated. It very well may be that I'm not aware of some config that is required but after poring over the react native docs and various articles on this topic, I'm pretty stumped.

**Comment by maicki** [comment]
@eddieowens Hey - could you provide an example that would show the issue? Would make it easier to debug. Thanks!

**Comment by eddieowens** [comment]
@maicki Sure thing. [myapp](https://github.com/eddieowens/myapp), [mylib](https://github.com/eddieowens/mylib).

**Comment by maicki** [comment]
@eddieowens Certain things to change:
1. Add the lib as a dependency and not local dependency
2. As the native modules are created lazily you have to export a method or something from the native module until you can use it.

I cloned your repo and changed the stuff in there. Here are the changes:
[myapp_and_mylib.zip](https://github.com/frostney/react-native-create-library/files/2257888/myapp_and_mylib.zip)

**Comment by eddieowens** [comment]
@maicki yep you're right. Turns out you cannot export a module without any methods. I was just misled by react native's documentation. Closing the issue and thanks!

Also, you can still using `install-local` just as an FYI for anyone that stumbles across this.
