### ISSUE TITLE
react-native-create-library -p does not work

### ISSUE THREAD

**Issue by awe-mt** [frostney/react-native-create-library#83]
react-native-create-library -p XX my-library
While `RN` is the default prefix,
  it is recommended to customize the prefix.

📚  Created library in-app-card-provisioning in `./in-app-card-provisioning`.

However, `react-native-create-library --prefix` does work.

**Comment by maicki** [comment]
Will close this issue due to duplication of #84

**Comment by awe-mt** [comment]
Thanks, I created these during a period when Github was having some issues and I couldn't find this one to delete it.
