### ISSUE TITLE
'RCTBridgeModule.h' file not found

### ISSUE THREAD

**Issue by ademcan** [frostney/react-native-create-library#87]
I am creating a new issue as I cannot open the closed one. It seems that once the project is created React is not linked properly and give me the following error in the automatically generated header file: 'RCTBridgeModule.h' file not found
I am running High Sierra with Xcode 10.

Steps to reproduce:
react-native-create-library test
cd react-native-test
npm install
npm link
open ios/test.xcworkspace -> error in the RNTest.h file

Thank you

**Comment by maicki** [comment]
hey! - It's not possible to build the library within the xcodeworkspace instead link it into a project and develop in there.

**Comment by ademcan** [comment]
Ok, I see, it makes sense. I indeed managed to use it into a project, but thought as a first step to build it alone... thank you for your help @maicki

**Comment by malikmani** [comment]
What about if you want to write the unit tests for the library? Will you be doing that into another project?

@maicki @ademcan
