### ISSUE TITLE
react-native-create-library command does not create a MainActivity.java

### ISSUE THREAD

**Issue by jerinho** [frostney/react-native-create-library#88]
react-native-create-library command does not created MainActivity.java file. Only ...Module.java and ...Package.java created. And also an empty AndroidManifest.xml

Why?

**Comment by maicki** [comment]
Hey, did you create the library from master? The version on npm unfortunately is really outdated: #78

**Comment by jerinho** [comment]
created it directly from command. here some details
- react-native-create-library@3.1.2
- npm : 6.4.1
- react-native-cli : 2.0.1
- react-native: 0.57.5

**Comment by maicki** [comment]
Try out creating it from master. As said above the npm version is pretty old, unfortunately I don't have the permissions to push a new version.

**Comment by jerinho** [comment]
ok. now i'm understand. we need to create a react-native app first using `react-native init` before react-native-create-library. they should fix the documentation

**Comment by jerinho** [comment]
> Hey, did you create the library from master? The version on npm unfortunately is really outdated: #78

how do you know i used npm?. because i'm pretty sure i used yarn

**Comment by maicki** [comment]
What I meant is if you installed `react-native-create-library` from the npm registry. `yarn` uses the npm registry to install packages.

**Comment by jerinho** [comment]
> ok. now i'm understand. we need to create a react-native app first using `react-native init` before react-native-create-library. they should fix the documentation

unfortunately this not working either. it asking for gradle-wrappers version of 2.2 and revert build tools version from latest one to the oldest one possible. if i change it back manually the compilation fail saying com.reactlibrary.MyActivity not found

**Comment by jerinho** [comment]
> Hey, did you create the library from master? The version on npm unfortunately is really outdated: #78

i just followed all of your quiet simple instructions on readme section. unless it's well-documented, i need some information from somewhere how to use the command from this repo instead of that outdated command from an latest updated npm

**Comment by jerinho** [comment]
> Try out creating it from master. As said above the npm version is pretty old, unfortunately I don't have the permissions to push a new version.

i guess it's from master
`npm i -g git+https://github.com/frostney/react-native-create-library.git`

**Comment by jerinho** [comment]
i close this issue as it's a misunderstanding. i suggest you to edit the instruction of how to use this repo. i've wrote some steps to follow in issue #89 

thank you for all your responses 😺
