### ISSUE TITLE
blank line at top of xcodeproj/project.pbxproj file breaks react-native link

### ISSUE THREAD

**Issue by Traviskn** [frostney/react-native-create-library#9]
While testing the installation process of a library I created with this tool, running `react-native link` produced an error 'Expected "{" found "/"'.  This is because there is an extra blank line at the top of the xcodeproj/project.pbxproj file that is confusing the link command.  After removing the blank line, the link command worked without errors.

**Comment by frostney** [comment]
Hi @Traviskn, thank you so much for the report.

**Comment by frostney** [comment]
Hi @Traviskn, would you mind checking if #10 would fix the problem?

**Comment by Traviskn** [comment]
Thanks @frostney, I've tested and #10 fixes this problem - react-native link works great!

**Comment by frostney** [comment]
Thank you so much for testing. I'll release a new version once I got home.

**Comment by frostney** [comment]
I just released version 1.0.2 which includes the fix. Thank you again for testing, much appreciated 👍

**Comment by Traviskn** [comment]
No problem, thanks for being so responsive!  Thanks to your library, I got my first react native npm package published: https://www.npmjs.com/package/react-native-uuid-generator  🎉
